name: release

on:
  push:
    tags: ["*"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          artifacts: "ImPlay-*/*"
          body: |
            # Install
            ## Windows
            - MSI
              - Download the msi executable
              - Run the MSI installer
              - Run ImPlay from Start Menu
            - Zip
              - Download the windows zip
              - Extract the zip
              - Run `ImPlay.exe`
            ## macOS
            - Download the dmg file
            - Double click the dmg to show it's contents
            - Drag ImPlay to `Applications` folder
            - Run ImPlay from Launchpad
            ## Linux
            - Debian Package
              - Download the deb file
              - Install: `sudo apt install ./ImPlay-*.deb`
              - Run `ImPlay`
            - AppImage
              - Download the AppImage file
              - Run `chmod u+x ImPlay-*.AppImage && ./ImPlay-*.AppImage`